Scheduler and mail sender added
matigastirami/stock-checker pull request #7
Opened 2021-07-27 23:30 UTC by ezeallio

- Scheduler option to check the stock of a product using cron format (if the user doesn't set a config, the package will check every 5 minutes by default)

- Option to add an email to notify about the stock of a product

- Options added into the README file and some refactor

2021-07-28 00:00 UTC, tompais reviewed
Dejo algunos comentarios que son más preguntas y otras asombrado de lo lindo que es Node. Cada vez me gusta más.

2021-07-28 00:00 UTC, tompais commented on README.md
> +--help                  Show help
Me gusta

2021-07-28 00:00 UTC, tompais commented on bin/index.js
> +  const rule = schedulerTime || "*/5 * * * *";
Wow. Pensaba que usar un `||` te devolvía una condición booleana y que para elegir entre una y otra tendrías que utilizar algún operador como `?`. Interesante...

2021-07-28 00:00 UTC, tompais commented on bin/index.js
> +  });
Quizás toda esta lógica, para que no esté en el index podamos moverla a otro archivo y, como mencionó en su momento @matigastirami , que el index principal solo tenga la responsabilidad de hacer el llamado a la función principal que vamos a terminar importando. Que, en este casso, va a ser `checkAndNotifyStock`

2021-07-28 00:00 UTC, tompais commented on helpers/mailSender.js
> +            pass: "", //set password
Si mal no entiendo, este sería el mail con el cual la librería se loguearía para notificar al usuario que hay stock.

No se si valdría poner los comentaarios con un TODO.
```suggestion
            user: "", // TODO: set email
            pass: "", // TODO: set password
```

Y/o agregar al README que es importante para usar el script agregar el mail o contraseña coon el cual se quiere notificar.

No sé qué opina @matigastirami

2021-07-28 00:39 UTC, ezeallio commented on bin/index.js
> +  });
Mmm habría que verlo bien pero capaz se puede

2021-07-28 00:42 UTC, ezeallio commented on helpers/mailSender.js
> +            pass: "", //set password
Si, tendría que ser con TODO y aclarar en el README eso

2021-07-28 02:35 UTC, matigastirami commented on bin/index.js
> +  const rule = schedulerTime || "*/5 * * * *";
Si @tompais, en JS el operador || tiene ambas funciones, pero en el standard 2020 agregaron el operador ?? que es más óptimo, entonces esa sentencia podría reemplazarla por 

`schedulerTime ?? "*/5 * * * *"`

De todos modos así como está no está mal y anda.

2021-07-28 02:37 UTC, matigastirami commented on bin/index.js
> +  const rule = schedulerTime || "*/5 * * * *";
Una cosa que sí cambiaría sería ese "*/5 * * * *" hardcodeado. Podemos agregar un archivo constants.js en los helpers y que solo haga exports de este tipos de strings, por ejemplo:

export const DEFAULT_CRON_STRING = "*/5 * * * *";

2021-07-28 02:38 UTC, matigastirami commented on bin/index.js
> +  });
Efectivamente, lo que dice Tomás, igual recién estamos armando esta lib. En estos días me voy a poner con la configuración para subirla a NPM y usarla para hacer alguna cosa interesante con React/React-Native

2021-07-28 02:40 UTC, matigastirami commented on helpers/mailSender.js
> +            pass: "", //set password
@ezeallio hay una lib en npm que se llama config que te permite agregar un archivo config.json dentro de un directorio /config. Con esta podés hacer algo así en tus archivos:

import config from "config";

...
user: config.get("EMAIL_USER")
...

También está la lib dotenv que me gusta más, pero eso ya va más en gustos.

Por otro lado deberíamos ver como hacer el handling de esto porque cada usuario que la use va a tener un mail diferente y en caso de poner todo acá estaríamos exponiendo data de usuarios.

2021-07-28 02:42 UTC, matigastirami requested changes
Ver los comments...

2021-07-28 03:33 UTC, tompais commented on bin/index.js
> +  const rule = schedulerTime || "*/5 * * * *";
Me gusta lo que proponés y me parecía que existía ese operador. Buenísimo. En Kotlin también existe, pero se escribe así `?:`, si bien la funcionalidad es la misma.

2021-07-29 01:03 UTC, matigastirami approved these changes

2021-07-29 01:04 UTC, merged